on:
  push:
    branches:
      - master
      - main
  release:
    types:
      - created

name: Publish NPM package
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: npm ci
        run:  npm ci
      - name: npm run build
        run:  npm run build
      - name: npm run test
        run: npm run test
      - name: npm run check-api
        run: npm run check-api
      - name: print diff if failed
        if: ${{ failure() }}
        run: git diff

      - name: Publish
        uses: menduz/oddish-action@master
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
