on:
  push:
    branches:
      - master
      - main
  release:
    types:
      - created

name: Publish NPM package
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: install
        run:  npm ci
      - name: build
        run:  npm run build
      - name: test
        run: npm run test
      - name: Publish
        uses: menduz/oddish-action@master
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
